// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turbo_Download_Manager.Database;

#nullable disable

namespace Turbo_Download_Manager.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240204181502_added group table")]
    partial class addedgrouptable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Turbo_Download_Manager.Models.DownloadGroupModel", b =>
                {
                    b.Property<string>("GroupID")
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentByte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartByte")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupID");

                    b.HasIndex("FileId");

                    b.ToTable("DownloadGroupsModels");
                });

            modelBuilder.Entity("Turbo_Download_Manager.Models.FileDownloadEntry", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDownloadDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("FileId");

                    b.ToTable("FileDownloadEntries");
                });

            modelBuilder.Entity("Turbo_Download_Manager.Models.DownloadGroupModel", b =>
                {
                    b.HasOne("Turbo_Download_Manager.Models.FileDownloadEntry", "FileDownloadEntry")
                        .WithMany("DownloadThreadEntrys")
                        .HasForeignKey("FileId");

                    b.Navigation("FileDownloadEntry");
                });

            modelBuilder.Entity("Turbo_Download_Manager.Models.FileDownloadEntry", b =>
                {
                    b.Navigation("DownloadThreadEntrys");
                });
#pragma warning restore 612, 618
        }
    }
}
